i made calendar
Orobinsk/secret_project pull request #30
Opened 2024-10-29 18:10 UTC by mbrita

сделала календарик премьер

2024-10-29 19:16 UTC, Orobinsk requested changes

2024-10-29 19:16 UTC, Orobinsk commented on src/api/apiTypes/apiListsTypes.ts
> +export interface IResponseLists<T> extends IResponseList<T> {
нужно переименовать в IResponseUpcomingMovies и использовать его

2024-10-29 19:16 UTC, Orobinsk commented on src/api/apiTypes/apiTypes.ts
> +  dates?: IDateRange;
если будем использовать IResponseUpcomingMovies то dates тут не нужно

2024-10-29 19:16 UTC, Orobinsk commented on src/api/apiTypes/apiTypes.ts
> +export interface IDateRange {
повтор с тем что в [apiListsTypes.ts](https://github.com/Orobinsk/secret_project/pull/30/files#diff-c21a3c995eff31dd02f06140f86b0e1c6d9c7ae54804e4976cfe559f477a76b1)

2024-10-29 19:16 UTC, Orobinsk commented on src/components/releaseCalendar/ReleaseCalendar.tsx
давай называть папку тоже с большой буквы

2024-10-29 19:16 UTC, Orobinsk commented on src/components/releaseCalendar/ReleaseCalendar.tsx
> +const MONTHNAMES = [
тут нужно в camelCase потому что это не какие-то параметры которые используем повсюду, а только в этом компоненте

2024-10-29 19:16 UTC, Orobinsk commented on src/components/releaseCalendar/ReleaseCalendar.tsx
> +        sort_by: 'primary_release_date.asc',
sort by тоже нужно добавить в API_MOVIE_LIST_PARAMS. При чем у него ведь есть конкретные варианты. Нужно подумать как тут лучше это оформить

2024-10-29 19:16 UTC, Orobinsk commented on src/components/releaseCalendar/createReleaseCalendarStyles.ts
> +    borderBottom: `0.5px solid ${theme.palette.text.secondary}`,
боттом 05 px. тут точно все норм?

2024-10-29 19:16 UTC, Orobinsk commented on src/pages/MainPage/MainPage.tsx
> +      {/* {movieList?.results.map((movie) => <MovieItem key={movie.id} movie={movie} />)} */}
давай отсюда вообще уберем все что закомментировано. Просто сам файл компонента оставим пока: хоть он нигде и не используется

2024-10-30 19:14 UTC, mbrita commented on src/api/apiTypes/apiTypes.ts
> +  dates?: IDateRange;
ok

2024-10-30 19:14 UTC, mbrita commented on src/api/apiTypes/apiListsTypes.ts
> +export interface IResponseLists<T> extends IResponseList<T> {
ok

2024-10-30 19:14 UTC, mbrita commented on src/api/apiTypes/apiTypes.ts
> +export interface IDateRange {
ok

2024-10-30 19:14 UTC, mbrita commented on src/components/releaseCalendar/ReleaseCalendar.tsx
> +const MONTHNAMES = [
ok

2024-10-30 19:15 UTC, mbrita commented on src/components/releaseCalendar/ReleaseCalendar.tsx
> +        sort_by: 'primary_release_date.asc',
ok

2024-10-30 19:15 UTC, mbrita commented on src/components/releaseCalendar/createReleaseCalendarStyles.ts
> +    borderBottom: `0.5px solid ${theme.palette.text.secondary}`,
это изменила

2024-10-30 19:15 UTC, mbrita commented on src/pages/MainPage/MainPage.tsx
> +      {/* {movieList?.results.map((movie) => <MovieItem key={movie.id} movie={movie} />)} */}
давай

2024-10-30 20:31 UTC, Orobinsk requested changes

2024-10-30 20:31 UTC, Orobinsk commented on src/components/releaseCalendar/ReleaseCalendar.tsx
> +        sort_by: 'primary_release_date.asc',
не исправлено. пиши комментарии после того как исправила и запушила

2024-10-30 20:31 UTC, Orobinsk commented on src/components/releaseCalendar/ReleaseCalendar.tsx
не сохранилось то что ты переименовала папку. поэтому падает vercel

2024-10-31 09:58 UTC, mbrita commented on src/components/releaseCalendar/ReleaseCalendar.tsx
> +        sort_by: 'primary_release_date.asc',
исправила

2024-10-31 09:58 UTC, mbrita commented on src/components/releaseCalendar/ReleaseCalendar.tsx
> +        sort_by: 'primary_release_date.asc,popularity.asc',
исправила

2024-10-31 14:53 UTC, Orobinsk requested changes

2024-10-31 14:53 UTC, Orobinsk commented on src/components/ReleaseCalend/ReleaseCalendar.tsx
> +        <Pagination
на мобильном разрешении пагинация выстраивается в 2 строки
![image](https://github.com/user-attachments/assets/d348c6e6-e80f-468b-a5c1-f6c5af8ae831)

2024-10-31 18:24 UTC, mbrita commented on src/components/ReleaseCalend/ReleaseCalendar.tsx
> +const RELEASE_DATE = new Date().toISOString().split('T')[0];
ok

2024-10-31 18:25 UTC, mbrita commented on src/components/ReleaseCalend/ReleaseCalendar.tsx
> +  const handleChange = (event: React.ChangeEvent<unknown>, value: number) => {
ok

2024-10-31 18:25 UTC, mbrita commented on src/components/ReleaseCalend/ReleaseCalendar.tsx
> +  const currentYear = new Date().getFullYear();
ok

2024-10-31 18:27 UTC, mbrita commented on src/constants.ts
> +export enum SortByOptions {
ok

2024-10-31 18:32 UTC, mbrita commented on src/components/ReleaseCalend/ReleaseCalendar.tsx
> +  const currentYear = new Date().getFullYear();
эти выносить нельзя -  const theme = useTheme();
  const styles = createReleaseCalendarStyles(theme);

2024-10-31 18:35 UTC, mbrita commented on src/components/ReleaseCalend/ReleaseCalendar.tsx
> +          <Typography variant="h4" color={theme.palette.text.primary} sx={styles.releaseHeader}>
давай

2024-10-31 18:47 UTC, mbrita commented on src/components/ReleaseCalend/ReleaseCalendar.tsx
> +        <Pagination
done

2024-10-31 18:53 UTC, Orobinsk requested changes

2024-10-31 18:53 UTC, Orobinsk commented on src/components/ReleaseCalend/ReleaseCalendar.tsx
> +          <Typography variant="h4" color={theme.palette.text.primary} sx={styles.releaseHeader}>
опять написала комментарий что исправила но не исправила!

2024-10-31 19:49 UTC, Orobinsk approved these changes

2024-10-31 20:09 UTC, merged