fix carousel adaptiv
Orobinsk/secret_project pull request #31
Opened 2024-10-29 18:43 UTC by mbrita

починила адаптив для маленьких экранов

2024-10-29 18:54 UTC, Orobinsk requested changes

2024-10-29 18:54 UTC, Orobinsk commented on src/components/carousel/Carousel.tsx
> +  const isSmallScreen = useMediaQuery('(max-width:600px)');
тут можно использовать значение breakpoint из темы. Вроде того как для css свойств компонентов пишем

2024-10-29 18:54 UTC, Orobinsk commented on src/components/carousel/Carousel.tsx
- на ширине 600-630 px отображается 4 изображения в столбец. 
- на ширине  870-1115 отображается не очень красиво в 2 строки где во второй всего 1 элемент
![image](https://github.com/user-attachments/assets/459a1867-d78e-4b22-9731-9f20fd04b48b)

2024-10-30 10:31 UTC, mbrita commented on src/components/carousel/Carousel.tsx
настроила

2024-10-30 14:21 UTC, Orobinsk requested changes

2024-10-30 14:21 UTC, Orobinsk commented on src/components/carousel/Carousel.tsx
на ширине 603 - 630 отображаются 2 картинки друг под другом

2024-10-30 14:21 UTC, Orobinsk commented on src/components/carousel/Carousel.tsx
> +  const ITEMSPERPAGE = isSmallScreen ? 1 : isMediumScreen ? 2 : 4;
нельзя использовать  вложенные тернарные операторы

2024-10-30 14:31 UTC, Orobinsk requested changes

2024-10-30 14:31 UTC, Orobinsk commented on src/components/App.tsx
> +    <Container maxWidth={false} disableGutters sx={{ bgcolor: '#12161a', minHeight: '100vh' }}>
оказывается vercel не подгружает app.css. Можешь сама попробовать решить эту проблему или я после после посмотрю.

этот контейнер соответственно не нужен

2024-10-30 14:56 UTC, Orobinsk commented on src/components/App.tsx
> +    <Container maxWidth={false} disableGutters sx={{ bgcolor: '#12161a', minHeight: '100vh' }}>
я исправил это в [MR33](https://github.com/Orobinsk/secret_project/pull/33)

2024-10-30 15:49 UTC, mbrita commented on src/components/carousel/Carousel.tsx
> +  const ITEMSPERPAGE = isSmallScreen ? 1 : isMediumScreen ? 2 : 4;
исправила

2024-10-30 15:49 UTC, mbrita commented on src/components/carousel/Carousel.tsx
исправила

2024-10-30 15:58 UTC, Orobinsk approved these changes

2024-10-30 16:48 UTC, merged