Added the ability to save the URL
Orobinsk/secret_project pull request #42
Opened 2024-11-05 19:21 UTC by mbrita

2024-11-05 21:25 UTC, Orobinsk requested changes

2024-11-05 21:25 UTC, Orobinsk commented on src/pages/ListOfMovies/ListOfMovies.tsx
> +  useEffect(() => {
тут должно быть без useEffect. в useState начальное состояние указывается по другому. такая реализацыя вызывает перерендеры.

2024-11-05 21:25 UTC, Orobinsk commented on src/pages/ListOfMovies/ListOfMovies.tsx
> +      setSearchParams((prevParams) => {
когда я выбираю жанр это сбрасывает сортировку. нужно разобраться в чем причина и исправить

2024-11-05 21:25 UTC, Orobinsk commented on src/pages/ListOfMovies/ListOfMovies.tsx
>    const [page, setPage] = useState(1);
нужно добавить в параметры и страницу. это нужно чтобы была возможность поделиться конкретной страницей

2024-11-06 10:31 UTC, mbrita commented on src/pages/ListOfMovies/ListOfMovies.tsx
>    const [page, setPage] = useState(1);
ok, done

2024-11-06 10:31 UTC, mbrita commented on src/pages/ListOfMovies/ListOfMovies.tsx
> +      setSearchParams((prevParams) => {
ok, done

2024-11-06 10:32 UTC, mbrita commented on src/pages/ListOfMovies/ListOfMovies.tsx
> +  useEffect(() => {
ok, done

2024-11-06 16:03 UTC, Orobinsk approved these changes

2024-11-06 16:48 UTC, merged