add person page
Orobinsk/secret_project pull request #46
Opened 2024-11-09 12:08 UTC by mbrita

сделала страницу для актера - пока драфт, буду дополнять

2024-11-09 20:31 UTC, mbrita commented on src/api/apiTypes/apiPersonTypes.ts
> +export interface IChange {
done

2024-11-09 20:31 UTC, mbrita commented on src/pages/ActorsPage/ActorsPage.tsx
> +  const PARAMS = [
ok

2024-11-09 20:32 UTC, mbrita commented on src/pages/ActorsPage/ActorsPage.tsx
> +          component="img"
даже не знаю - сделала сейчас img

2024-11-09 20:32 UTC, mbrita commented on src/pages/ActorsPage/ActorsPage.tsx
> +          src={`https://image.tmdb.org/t/p/w500${actor?.profile_path}`}
ok

2024-11-09 20:32 UTC, mbrita commented on src/pages/ActorsPage/ActorsPage.tsx
> +  const [open, setOpen] = useState(false);
стала на порядок умней

2024-11-09 21:05 UTC, Orobinsk requested changes

2024-11-09 21:05 UTC, Orobinsk commented on src/pages/ActorsPage/ActorsPage.tsx
> +          posters={actor?.images?.profiles || []}
выходит что если profiles отсутвует то то картинок нет, но при этом мы можем открыть пустую модалку? Давай лучше если этого поля нет то вообще не будем рендерить <PosterModal

2024-11-09 21:05 UTC, Orobinsk commented on src/pages/ActorsPage/ActorsPage.tsx
> +          : 'Unknown'}
может вместо "Unknown" просто не будем вообще отрисовывать Date of Birth?
 То же самое и в других случаях если информации нет

2024-11-09 21:05 UTC, Orobinsk commented on src/pages/ActorsPage/ActorsPage.tsx
> +      <PosterModal open={open} handleClose={handleClose} posters={actor?.images?.profiles || []} />
это второй постер модал в компоненте. убери

2024-11-10 16:59 UTC, Orobinsk requested changes

2024-11-10 16:59 UTC, Orobinsk commented on src/types/personTypes.ts
> +  tv_credits: ITvResponse;
это поле не обязательное

2024-11-10 17:41 UTC, merged