Mb router test
Orobinsk/secret_project pull request #55
Opened 2024-11-18 12:52 UTC by mbrita

написала 🚬 смок-тест для проверки рендеринга страниц

2024-11-18 14:01 UTC, Orobinsk requested changes

2024-11-18 14:01 UTC, Orobinsk commented on src/pages/MainPage/MainPage.tsx
> +    <div data-testid="main-page">
мне кажется по семантике должен быть тег main. Проверь

2024-11-18 19:51 UTC, mbrita commented on src/types/tests.ts
> +export interface TestProps {
удалила

2024-11-30 09:19 UTC, Orobinsk approved these changes

2024-11-30 09:19 UTC, merged